name: discord.dart
description: A Dart wrapper to interact with the Discord API.
authors:
- Dylan Ogle <dylan@funo.io>
homepage: https://github.com/DelxHQ/discord.dart
repository: https://github.com/DelxHQ/discord.dart
issue_tracker: https://github.com/DelxHQ/discord.dart/issues

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  logging: "^0.11.3+2"
  w_transport: ^3.2.8